### PR TITLE
fix: big file upload

### LINKED ISSUE #75: Axios error on big file upload
I tried to upload a bigger file (32MB) calling `uploadFile` function of the Bee class cause safeAxios error: `Request body larger than maxBodyLength limit`.

### PR DESCRIPTION
**Pull request by agazso**
Fixes #75

### CODE REVIEW

File: src/utils/safeAxios.ts [hunk 1]
```diff
@@ -5,7 +5,11 @@ axios.defaults.adapter = require('axios/lib/adapters/http') // https://stackover
 
 export async function safeAxios<T>(config: AxiosRequestConfig): Promise<AxiosResponse<T>> {
   try {
-    const response = await axios(config)
+    const response = await axios({
+      maxContentLength: Infinity,
+      maxBodyLength: Infinity,
+      ...config,
+    })
```
Comment (vojtechsimetka) [inline src/utils/safeAxios.ts:12]: How does having the `maxContentLength` and `maxBodyLength` here helps over passing it in the `upload` function?

**Review by vojtechsimetka — APPROVED** [review]

File: src/utils/safeAxios.ts (hunk 1 above)
Comment (agazso) [reply src/utils/safeAxios.ts:12]: `safeAxios` is a wrapper that is called from everywhere where we use `axios`. So changing it here works for all endpoint, we don't have to change all individual endpoints. Please note that this also disables the limits for downloading  according to the [documentation](https://github.com/axios/axios).

I just vaguely understand what's the point of this feature in axios (and it seems it's node only) but I think it's better to not expose it as is to our users. If we have a use-case where there is a point of limiting it, we can always expose an option that matches the context better.
